const TYPE_INFO = {
    CREATE: 'CREATE',
    EDIT: 'EDIT',
    DELETE: 'DELETE',
    CURRENT_NOTE: 'CURRENT_NOTE',
    ERROR: 'ERROR',
    DATE_ONLY: 'DATE_ONLY',
    DATE_AND_TIME: 'DATE_AND_TIME'
}

export default TYPE_INFO;